# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Banco de Curriculos
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Github Workshop
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: SBootstrap
github_username:  BlackrockDigital
facebook_username: StartBootstrap
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: Gastao Alves, Icarai
address_city: Niteroi
address_state: RJ
address_zip: 24220-000

# Build settings
markdown: kramdown
